package com.srots.presentation.navigation.model;

/**
 * Stable identifiers for presentation navigation destinations.
 */
public enum NavigationRouteId {

    OVERVIEW,
    DESIGN_SYSTEM,
    LOGIN,

    WORKSPACE,
    WORKSPACE_TASKS,
    WORKSPACE_PROJECTS,
    WORKSPACE_ISSUES,
    WORKSPACE_ACTIVITY,

    COMPANY,
    COMPANY_EMPLOYEES,
    COMPANY_TEAMS,
    COMPANY_DEPARTMENTS,
    COMPANY_ORGANIZATION,

    PROJECTS,
    PROJECT_DETAILS,
    TASKS,
    TASK_DETAILS,
    ISSUES,
    ISSUE_DETAILS,

    PRODUCTS,
    PRODUCT_DETAILS,
    SROTS_PRODUCT,
    SROTS_OVERVIEW,
    SROTS_ENGINEERING,
    SROTS_VERSIONS,
    SROTS_RELEASES,

    COMPTY,
    COMPTY_OVERVIEW,
    COMPTY_REQUIREMENTS,
    COMPTY_ENGINEERING,
    COMPTY_VERSIONS,
    COMPTY_RELEASES,
    COMPTY_ANALYTICS,

    ENGINEERING,
    ENGINEERING_REQUIREMENTS,
    ENGINEERING_DEVELOPMENT,
    ENGINEERING_BUILDS,
    ENGINEERING_ISSUES,

    VERSIONS,
    RELEASES,
    RELEASE_DETAILS,
    DEPLOYMENTS,

    SALES,
    SALES_LEADS,
    SALES_OPPORTUNITIES,
    SALES_CUSTOMERS,
    SALES_DEALS,

    SUPPORT,
    KNOWLEDGE,
    ANALYTICS,
    SETTINGS,
    PROFILE,
    PREFERENCES,

    UNKNOWN;

    public String id() {
        return name();
    }
}
